jelly_hardware:
    ### Joint configuration
    joint_names:
        - FL_hip_joint
        - FL_upper_leg_joint
        - FL_lower_leg_joint
        - FR_hip_joint
        - FR_upper_leg_joint
        - FR_lower_leg_joint
        - RL_hip_joint
        - RL_upper_leg_joint
        - RL_lower_leg_joint
        - RR_hip_joint
        - RR_upper_leg_joint
        - RR_lower_leg_joint

    odrive_ids:
        - id: 2069339B304B # Front Right
          axis1: FL_upper_leg_joint
          axis0: FL_lower_leg_joint

        - id: 2069339E304B # Rear Right
          axis0: RL_upper_leg_joint
          axis1: RL_lower_leg_joint

        - id: 206A3378304B # Rear Left
          axis1: RR_upper_leg_joint
          axis0: RR_lower_leg_joint

        - id: 206A3398304B # Front Left
          axis1: FR_upper_leg_joint
          axis0: FR_lower_leg_joint

        - id: 207C37823548 # Rear
          axis0: RL_hip_joint
          axis1: RR_hip_joint

        - id: 207C37863548 # Front
          axis0: FR_hip_joint
          axis1: FL_hip_joint


    base_link: base_link
    fl_link:   FL_foot_link
    fr_link:   FR_foot_link
    rl_link:   RL_foot_link
    rr_link:   RR_foot_link

    gear_ratio: 8.21
    joint_directions: [1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, 1.0]
    starting_joints: [-0.26, 0.0, 0.0, 0.26, 0.0, 0.0, -0.26, 0.0, 0.0, 0.26, 0.0, 0.0]

    mass: 0.1 # kg

jelly_control:
    speed: 0.8 # number between 0 and 1

    # force control settings
    pd_force_control: true
    kp: 6.1
    kd: 0.001

    height: 0.2
    clip_threshold: 0.1

    home_position:    [0.2, -0.7, 1.4, -0.2, -0.7, 1.4, 0.2, 0.7, -1.4, -0.2, 0.7, -1.4]
    rolling_position: [0.0, -1.3, 2.7, 0.0, -1.3, 2.7, 0.0, 1.3, -2.7, 0.0, 1.3, -2.7]
    # rolling_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    total_gait_count: 1800

    walking_gait:
        p1     : [1.85e-01, -8.5e-02, -3.94e-01]
        p2     : [-1.85e-01, -8.5e-02, -3.94e-01]
        offset : [0.07, 0, 0]
        beta   : 0.90

    turning_gait:
        p1     : [1.85e-01, 4.5e-02, -3.94e-01]
        p2     : [-1.85e-01, 4.5e-02, -3.94e-01]
