jelly_hardware:
    ### Joint configuration
    joint_names:
        - FL_hip_joint
        - FL_upper_leg_joint
        - FL_lower_leg_joint
        - FR_hip_joint
        - FR_upper_leg_joint
        - FR_lower_leg_joint
        - RL_hip_joint
        - RL_upper_leg_joint
        - RL_lower_leg_joint
        - RR_hip_joint
        - RR_upper_leg_joint
        - RR_lower_leg_joint

    odrive_ids:
        - id: 207C37823548
          axis1: FL_hip_joint
          axis2: FL_upper_leg_joint

        - id: 207C37823548
          axis1: FL_hip_joint
          axis2: FL_upper_leg_joint

        - id: 207C37823548
          axis1: FL_hip_joint
          axis2: FL_upper_leg_joint

        - id: 207C37823548
          axis1: FL_hip_joint
          axis2: FL_upper_leg_joint

        - id: 207C37823548
          axis1: FL_hip_joint
          axis2: FL_upper_leg_joint

        - id: 207C37823548
          axis1: FL_hip_joint
          axis2: FL_upper_leg_joint


    base_link: chassis
    fl_link:   FL_lower_leg
    fr_link:   FR_lower_leg
    rl_link:   RL_lower_leg
    rr_link:   RR_lower_leg

    gear_ratio: 8.1
    joint_directions: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    id_torque_gains: [1.12, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

    softstop_min_angles: [-3.3, -2.25, -2.6, -2.25, -2.6, -2.25, -2.6, -1.45]
    softstop_max_angles: [2.2, 0.5, 2.6, 0.5, 2.6, 0.2, 2.6, 1.45]
jelly_control:

    home_position: [-0.785398, -2.19, -1.570796, 0.0, 1.570796, -0.23, 0.0, 0.0]
    rolling_position: [-0.785398, -2.19, -1.570796, 0.0, 1.570796, -0.23, 0.0, 0.0]

    total_gait_count: 500

    walking_gait:
        p1     : [1.85e-01, 4.5e-02, -3.94e-01]
        p2     : [-1.85e-01, 4.5e-02, -3.94e-01]
        offset : [0.07, 0, 0]
        beta   : 0.85

    turning_gait:
        p1     : [1.85e-01, 4.5e-02, -3.94e-01]
        p2     : [-1.85e-01, 4.5e-02, -3.94e-01]
